version: '3.7'
services:

  database:
    build: ./database
    image: mutillidae/database:latest
    command: --default-authentication-plugin=mysql_native_password

  database_admin:
    depends_on:
    - database
    image: mutillidae/database_admin:latest
    build: ./database_admin
    ports:
    - 127.0.0.1:81:80

  www:
    depends_on:
    - database
    - ldap
    build: ./www
    image: mutillidae/www:latest
    volumes:
    # Make the Apache log files on the image available to localhost
    - "./www/var-log-apache2/:/var/log/apache2/"
    ports:
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443

  ldap:
    build: ./ldap
    image: mutillidae/ldap:latest
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  ldap_admin:
    depends_on:
    - ldap
    build: ./ldap_admin
    image: mutillidae/ldap_admin:latest
    ports:
    - 127.0.0.1:82:80
   
volumes:
  ldap_data:
  ldap_config:
